[project]
name = "titiler-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cachetools>=7.0.6",
    "h5netcdf>=1.8.1",
    "h5py>=3.16.0",
    "netcdf4>=1.7.4",
    "pillow>=12.2.0",
    "s3fs>=2026.3.0",
    "scipy>=1.17.1",
    "titiler-core>=2.0.2",
    "uvicorn>=0.46.0",
    "xarray>=2026.4.0",
    "zarr>=3.1.6",
]
